In [12]:
import sys
import numpy as np

sys.path.append('../')

import mandala
from mandala import Variable
from mandala.autodiff import functions as F

In [13]:
x = Variable(np.ones((3, 10, 10), dtype=np.float32))

In [14]:
h = F.log((2 * x) ** 3 + x - 1 * x / x)

In [15]:
y = F.relu(h).reshape(10, 3, 10)

In [16]:
y.backward(gy=y.data)

In [17]:
x.grad.data

array([[[ 6.49825478,  6.49825478,  6.49825478,  6.49825478,  6.49825478,
          6.49825478,  6.49825478,  6.49825478,  6.49825478,  6.49825478],
        [ 6.49825478,  6.49825478,  6.49825478,  6.49825478,  6.49825478,
          6.49825478,  6.49825478,  6.49825478,  6.49825478,  6.49825478],
        [ 6.49825478,  6.49825478,  6.49825478,  6.49825478,  6.49825478,
          6.49825478,  6.49825478,  6.49825478,  6.49825478,  6.49825478],
        [ 6.49825478,  6.49825478,  6.49825478,  6.49825478,  6.49825478,
          6.49825478,  6.49825478,  6.49825478,  6.49825478,  6.49825478],
        [ 6.49825478,  6.49825478,  6.49825478,  6.49825478,  6.49825478,
          6.49825478,  6.49825478,  6.49825478,  6.49825478,  6.49825478],
        [ 6.49825478,  6.49825478,  6.49825478,  6.49825478,  6.49825478,
          6.49825478,  6.49825478,  6.49825478,  6.49825478,  6.49825478],
        [ 6.49825478,  6.49825478,  6.49825478,  6.49825478,  6.49825478,
          6.49825478,  6.4982547

In [4]:
y.backward()

In [5]:
x.grad.data

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.])

In [6]:
y = x.reshape(3, 4)

In [7]:
y.backward(y.data)

In [8]:
x.grad.data

array([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])